[package]
name = "tabletop"
version = "0.1.0"
authors = ["Robin Toncourt <robin.toncourt@gmail.com>"]
edition = "2024"
include = ["**/*.rs", "Cargo.toml"]
rust-version = "1.88"

[dependencies]
bevy = { version= "0.17.2", default-features = false, features = [
    "bevy_winit", "bevy_sprite", "bevy_ui", "bevy_text", "bevy_picking", "png", "webgl2", "x11",
    "bevy_log", "debug"
] }
bevy_matchbox = "0.13.0"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
strip = "debuginfo"
overflow-checks = false
panic = "abort"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[features]
dev = ["bevy/dynamic_linking"]
